### PR TITLE
Rosa's Changes - Name and City

### PR DESCRIPTION
**Pull request by rosachen3**
Created pull requests and pushed changes to branch

### CODE REVIEW

**Comment by crystalchen8** [comment]
Looks great Rosa.

**Comment by bananya3** [comment]
Commence merge

**Review by crystalchen8 — APPROVED** [review]
This looks great. No problem

**Review by bananya3 — COMMENTED** [review]
Nice

**Review by bananya3 — APPROVED** [review]
Nice x2

**Pull request merged**
